# Generated by Django 5.0.6 on 2024-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('joindate', models.DateField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
